### ISSUE TITLE
_mysql_exceptions.DatabaseError: ERROR: failed to connect to the MySQL database

### ISSUE THREAD

**Issue by wangj2009** [JBerthelier/PiRATE#25]
Dear Jeremy,
     The PiRATE could run RepeatScout, SINE-finder, LTRharvest, TE-hmmer, RepeatMasker. But It could not run TEdenovo, Helsearch, MITE-Hunter, MGEScan-nonLTR.
     When I run PASTEC, it have errors as following, even if I logged in as administrator@pba.fr.

2019-11-23 03:24:26 - PASTEClassifier - INFO - START PASTEClassifier parallelized 2019-11-23 03:24:26 - PASTEClassifier - INFO - Fasta file name: genome.fa 2019-11-23 03:24:26 - PASTEClassifier - INFO - Running STEP 1 of PASTEClassifier parallelized: DetectTEFeatures START DetectTEFeatures_parallelized Fasta file name: genome.fa split the sequences in batches Homogeneous in size 20kbp launch the programs on each batch 2019-11-23 03:24:35 - DbMySql - ERROR - ERROR 1049: Unknown database 'PASTEC_galaxy'

Fatal error: Exit code 1 ()
ERROR 1008 (HY000) at line 1: Can't drop database 'PASTEC_galaxy'; database doesn't exist
Traceback (most recent call last):
  File "/home/jeremy/Pipeline/REPET_2.5/bin/PASTEClassifier.py", line 405, in <module>
    iPASTEClassifier.run()
  File "/home/jeremy/Pipeline/REPET_2.5/bin/PASTEClassifier.py", line 384, in run
    iDF.run()
  File "/home/jeremy/Pipeline/REPET_2.5/commons/tools/DetectTEFeatures_parallelized.py", line 226, in run
    iDb = DbFactory.createInstance()
  File "/home/jeremy/Pipeline/REPET_2.5/commons/core/sql/DbFactory.py", line 37, in createInstance
    return DbMySql(cfgFileName = configFileName, verbosity = verbosity)
  File "/home/jeremy/Pipeline/REPET_2.5/commons/core/sql/DbMySql.py", line 166, in __init__
    raise DatabaseError(msg)
_mysql_exceptions.DatabaseError: ERROR: failed to connect to the MySQL database

**Comment by JBerthelier** [comment]
Dear wangj, 

According to the error, it seems that your MySql database of PASTEC no more existe in your 
PiRATE-VM. You need this MySql database to stock data while you are using PASTEC.

You can re-create by running this code in the konsol: 

**mysql -u root --password=jeremy07 -e "create database PASTEC_galaxy"**

This should solve your problem for PASTEC 

Other users have also somes problems with Helsearch and  MGEScan-nonLTR, which seems not working on every genome assembly.

TEdenovo should work, please be careful to submit a fasta file with 60 bp in lenght and with header containing only letters (a to z), numbers (0-9) and underscore ( _ ) 
Example= Contig_1  

Best,

Jeremy
